---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: konflux-devprod-admins
  namespace: konflux-devlake
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - update
      - patch
      - delete

  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - delete

  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - delete

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: konflux-devprod-admins
  namespace: konflux-devlake
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: konflux-devprod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: konflux-devprod-admins
