---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: group-sync-operator
resources:
- ../base
components:
  - ../k-components/internal-ldap-url
  - ../k-components/konflux-ldap-sa
  - ../k-components/mtls-ca-validators
