---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: internal-services
  namespace: internal-services
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: konflux-release-team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: component-maintainer

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: internal-services
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: konflux-release-team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: internal-service-request-role

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: internal-service-request-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: internal-service-request-role
subjects:
  - kind: ServiceAccount
    name: internal-service-request-service-account
    namespace: internal-services
