---
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: releng-vault
spec:
  provider:
    vault:
      auth:
        appRole:
          path: approle
          roleId: 7ac0afae-d45e-a5d4-d277-d4482efc0cf1
          secretRef:
            key: secret_id
            name: konflux-release-internal-services-vault
      path: releng
      server: 'https://vault.devshift.net'
      version: v2
---
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: konflux-vault
spec:
  provider:
    vault:
      auth:
        appRole:
          path: approle
          roleId: 7ac0afae-d45e-a5d4-d277-d4482efc0cf1
          secretRef:
            key: secret_id
            name: konflux-release-internal-services-vault
      path: konflux
      server: 'https://vault.devshift.net'
      version: v2
---
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: stonesoup-vault
spec:
  provider:
    vault:
      auth:
        appRole:
          path: approle
          roleId: 7ac0afae-d45e-a5d4-d277-d4482efc0cf1
          secretRef:
            key: secret_id
            name: konflux-release-internal-services-vault
      path: stonesoup
      server: 'https://vault.devshift.net'
      version: v2
---
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: hacbs-vault
spec:
  provider:
    vault:
      auth:
        appRole:
          path: approle
          roleId: 7ac0afae-d45e-a5d4-d277-d4482efc0cf1
          secretRef:
            key: secret_id
            name: konflux-release-internal-services-vault
      path: hacbs
      server: 'https://vault.devshift.net'
      version: v2
