---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openshift-pipelines
spec:
  generators:
    - clusters:
        values:
          sourceRoot: components/openshift-pipelines
          environment: base
          clusterName: ""
  template:
    metadata:
      name: smee-{{values.clusterName}}
    spec:
      project: default
      source:
        path: '{{values.sourceRoot}}/{{values.environment}}'
        repoURL: https://github.com/redhat-appstudio/infra-common-deployments.git
        targetRevision: main
      destination:
        namespace: smee
        server: '{{server}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: -1
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
