kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: component-maintainer
rules:
  - apiGroups:
      - operators.coreos.com
    resources:
      - installplans
    verbs:
      - get
      - list
      - update
      - patch
  - apiGroups:
      - ''
    resources:
      - serviceaccounts
    resourceNames:
      - pipeline
    verbs:
      - patch
      - get
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - create
      - get
      - list
      - watch
      - delete
  - apiGroups:
      - 'tekton.dev'
    resources:
      - 'pipelineruns'
    verbs:
      - '*' # needed till we figure out how to cleanup workspaces.
  - apiGroups:
      - results.tekton.dev
    resources:
      - results
      - records
      - logs
    verbs:
      - get
      - list
  - apiGroups:
      - ''
    resources:
      - pods/portforward
    verbs:
      - create
  - apiGroups:
      - 'apps'
    resources:
      - deployments
    verbs:
      - get
      - patch
      - delete
