apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dev-can-sync
rules:
  # ArgoCD Applications - view and sync permissions
  - apiGroups:
      - argoproj.io
    resources:
      - applications
      - applications/actions
      - applications/events
      - applications/exec
      - applications/logs
      - applications/operation
      - applications/rollback
      - applications/status
      - applications/sync
      - applicationsets
      - applicationsets/status
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  # ArgoCD Projects, Clusters, Repositories - view permissions
  - apiGroups:
      - argoproj.io
    resources:
      - appprojects
      - clusters
      - repositories
    verbs:
      - get
      - list
      - watch
  # Basic namespace and resource viewing permissions
  - apiGroups:
      - ''
    resources:
      - configmaps
      - endpoints
      - events
      - namespaces
      - persistentvolumeclaims
      - persistentvolumes
      - pods
      - services
    verbs:
      - get
      - list
      - watch
  # Deployment viewing permissions
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dev-can-sync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dev-can-sync
subjects: [] # added by patch to avoid duplicating the groups
