---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - component-maintainers.yaml
  - dev-can-sync.yaml
  - everyone-can-view.yaml
  - konflux-admins.yaml
patches:
  - path: everyone-can-view-patch.yaml
    target:
      name: dev-can-sync
      kind: ClusterRoleBinding
      group: rbac.authorization.k8s.io
      version: v1
  - path: everyone-can-view-patch.yaml
    target:
      name: everyone-view
      kind: ClusterRoleBinding
      group: rbac.authorization.k8s.io
      version: v1
  - path: everyone-can-view-patch.yaml
    target:
      name: everyone-view-cluster-version
      kind: ClusterRoleBinding
      group: rbac.authorization.k8s.io
      version: v1
  - path: everyone-can-view-patch.yaml
    target:
      name: everyone-view-cluster-monitoring
      kind: ClusterRoleBinding
      group: rbac.authorization.k8s.io
      version: v1
  - path: everyone-can-view-patch.yaml
    target:
      name: everyone-view-compute
      kind: ClusterRoleBinding
      group: rbac.authorization.k8s.io
      version: v1
