apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - path: approle-id-patch.yaml
    target:
      name: appsre-stonesoup-vault
      kind: ClusterSecretStore
      group: external-secrets.io
      version: v1beta1
