---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
components:
  - ../k-components/external-ldap-url
  - ../k-components/konflux-ldap-sa
  - ../k-components/mtls-ca-validators
