---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: all-application-sets
spec:
  project: default
  source:
    path: argo-cd-apps/overlays/base
    repoURL: https://github.com/redhat-appstudio/infra-common-deployments.git
    targetRevision: main
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      syncOptions:
        - CreateNamespace=true
